apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yellow-staging
resources:
- ../../../base
- ../resourcequota.yaml
- ../limitrange.yaml
namePrefix: yellow-
commonLabels:
  app.kubernetes.io/name: yellow
  app.kubernetes.io/instance: yellow-staging
  environment: staging
images:
- name: quay.io/davidaparicio/app
  newName: quay.io/davidaparicio/yellow
  newTag: 3.3.1
replicas:
- name: app
  count: 2
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "64Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "128Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "250m"
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: yellow.stg.127.0.0.1.nip.io
  target:
    kind: Ingress
