apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blue-development
resources:
- ../../../base
namePrefix: blue-
commonLabels:
  app.kubernetes.io/name: blue
  app.kubernetes.io/instance: blue-development
  environment: development
images:
- name: quay.io/davidaparicio/app
  newName: quay.io/davidaparicio/blue
  newTag: sha-2cce2c2
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "32Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "50m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "64Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "100m"
    - op: add
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
    - op: replace
      path: /spec/strategy/blueGreen/activeService
      value: blue-app
    - op: replace
      path: /spec/strategy/blueGreen/previewService
      value: blue-app-preview
    - op: replace
      path: /spec/strategy/blueGreen/prePromotionAnalysis/templates/0/templateName
      value: blue-app-health-check
  target:
    kind: Rollout
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: blue.dev.127.0.0.1.nip.io
  target:
    kind: Ingress
