apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blue-staging

resources:
  - ../../../base

namePrefix: blue-

commonLabels:
  app.kubernetes.io/name: blue
  app.kubernetes.io/instance: blue-staging
  environment: staging

images:
  - name: davidaparicio/app
    newName: davidaparicio/blue
    newTag: "2.1.0"

replicas:
  - name: app
    count: 2

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "64Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "250m"
    target:
      kind: Deployment
