apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blue-staging
resources:
- ../../../base/kustomization-bluegreen.yaml
namePrefix: blue-
commonLabels:
  app.kubernetes.io/name: blue
  app.kubernetes.io/instance: blue-staging
  environment: staging
images:
- name: quay.io/davidaparicio/app
  newName: quay.io/davidaparicio/blue
  newTag: 3.2.0
replicas:
- name: app
  count: 2
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "64Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "128Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "250m"
  target:
    kind: Rollout
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: blue.stg.127.0.0.1.nip.io
  target:
    kind: Ingress
