apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blue-staging
resources:
- ../../../base
namePrefix: blue-
commonLabels:
  app.kubernetes.io/name: blue
  app.kubernetes.io/instance: blue-staging
  environment: staging
images:
- name: quay.io/davidaparicio/app
  newName: quay.io/davidaparicio/blue
  newTag: 3.3.0
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "64Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "128Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "250m"
    - op: replace
      path: /spec/strategy/blueGreen/activeService
      value: blue-app
    - op: replace
      path: /spec/strategy/blueGreen/previewService
      value: blue-app-preview
    - op: replace
      path: /spec/strategy/blueGreen/prePromotionAnalysis/templates/0/templateName
      value: blue-app-health-check
  target:
    kind: Rollout
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: blue.stg.127.0.0.1.nip.io
  target:
    kind: Ingress
