apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blue-staging
resources:
- ../../../base
- ../../../base/pdb.yaml
- ../../../base/hpa.yaml
namePrefix: blue-
commonLabels:
  app.kubernetes.io/name: blue
  app.kubernetes.io/instance: blue-staging
  environment: staging
images:
- name: quay.io/davidaparicio/app
  newName: quay.io/davidaparicio/blue
  newTag: 3.3.1
replicas:
- name: app
  count: 2
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "64Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "128Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "250m"
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: blue.stg.127.0.0.1.nip.io
    - op: replace
      path: /spec/tls/0/hosts/0
      value: blue.stg.127.0.0.1.nip.io
    - op: replace
      path: /spec/tls/0/secretName
      value: blue-tls
  target:
    kind: Ingress
- patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 2
    - op: replace
      path: /spec/maxReplicas
      value: 6
  target:
    kind: HorizontalPodAutoscaler
