apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: git-sync-development
resources:
- ../../../base/git-sync-deployment.yaml
- ../../../base/git-sync-service.yaml
- ../../../base/git-sync-ingress.yaml
namePrefix: git-sync-
commonLabels:
  app.kubernetes.io/name: git-sync
  app.kubernetes.io/instance: git-sync-development
  environment: development
images:
- name: quay.io/davidaparicio/app
  newName: quay.io/davidaparicio/git-sync
  newTag: sha-17f3881
replicas:
- name: app
  count: 1
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "*/2 * * * *"
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "git-sync.dev.127.0.0.1.nip.io"
  target:
    kind: Ingress
