apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: landing-production
resources:
- ../../../base/landing
commonLabels:
  app.kubernetes.io/instance: landing-production
  environment: production
patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: color.prd.127.0.0.1.nip.io
  target:
    kind: Ingress
