name: Release

on:
  push:
    branches:
      - main
    paths:
      - build/Dockerfile
      - .release-please-manifest.json
      - CHANGELOG.md

permissions:
  contents: write
  issues: write
  pull-requests: write
#permissions: write-all

env:
  APP_NAME: color
  IMAGE_REPOSITORY: 'docker.io'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 #v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: simple
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

  publish:
    if: needs.release.outputs.release_created == 'true'
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - preprod
          - dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 #v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f #v3
      - name: Build and push image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ needs.release.outputs.tag_name }}-${{ matrix.env }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ needs.release.outputs.tag_name }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            GIT_COMMIT=${{ github.sha }}
    
