apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  labels:
    app.kubernetes.io/part-of: microsvcs
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: "128Mi"
    limits.cpu: "400m"
    limits.memory: "256Mi"
    pods: "4"
    services: "2"
    configmaps: "5"
    secrets: "5"
    persistentvolumeclaims: "1"
