apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microsvcs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - project: red
                - project: blue
                - project: green
                - project: yellow
          - list:
              elements:
                - env: development
                  autoSync: "true"
                - env: staging
                  autoSync: "true"
                - env: production
                  autoSync: "false"
  template:
    metadata:
      name: '{{.project}}-{{.env}}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: '{{.project}}'
        environment: '{{.env}}'
      annotations:
        kargo.akuity.io/authorized-stage: 'microsvcs:{{.project}}-{{.env}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: microsvcs
      source:
        repoURL: https://github.com/davidaparicio/microsvcs.git
        targetRevision: HEAD
        path: 'k8s/overlays/{{.env}}/{{.project}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.project}}-{{.env}}'
      syncPolicy:
        {{- if eq .autoSync "true" }}
        automated:
          prune: true
          selfHeal: true
        {{- end }}
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 3
