apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  labels:
    app.kubernetes.io/part-of: microsvcs
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "768Mi"
    limits.cpu: "2"
    limits.memory: "1536Mi"
    pods: "10"
    services: "3"
    configmaps: "10"
    secrets: "10"
    persistentvolumeclaims: "3"
