apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - rbac.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/part-of: microsvcs
  app.kubernetes.io/managed-by: argocd
