apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bluegreen-rollout.yaml
  - service.yaml
  - preview-service.yaml
  - ingress.yaml
  - analysis-template.yaml

commonLabels:
  app.kubernetes.io/part-of: microsvcs
  app.kubernetes.io/managed-by: argocd
