apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blue-production
resources:
- ../../../base/kustomization-canary.yaml
namePrefix: blue-
commonLabels:
  app.kubernetes.io/name: blue
  app.kubernetes.io/instance: blue-production
  environment: production
images:
- name: quay.io/davidaparicio/app
  newName: quay.io/davidaparicio/blue
  newTag: 3.0.0
replicas:
- name: app
  count: 3
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "128Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "200m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "256Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "500m"
  target:
    kind: Rollout
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: blue.prd.127.0.0.1.nip.io
  target:
    kind: Ingress
